#ifndef V_TYPE_PLANETARIUM_COMMANDER_NICK_DIALOGUES_H
#define V_TYPE_PLANETARIUM_COMMANDER_NICK_DIALOGUES_H

static const char* k_commander_nick_dialogues[30] = {
    "LISTEN UP, KID. TRUST YOUR SCOPES OVER GUT FEELING EVERY TIME. SPACE IS A COLD LIAR, AND HUNCHES WILL VECTOR YOU INTO ROCK. PLOT YOUR COURSE TWICE, THRUST ONCE, AND LIVE TO FLY AGAIN.",
    "FUEL IS YOUR LIFELINE, KID, AND AMMO DOES NOT GROW ON NEBULAE. EVERY BURST COUNTS, EVERY IDLE BURN STEALS TOMORROW'S ESCAPE. CONSERVE HARD, OR YOU DRIFT AS DUST WHILE THE STARS LAUGH.",
    "ONE BAD VECTOR, KID, AND THE VOID COLLECTS YOU FOR GOOD. CHECK NAV THREE WAYS BEFORE YOU COMMIT THRUST. FLY SMART, NOT SORRY.",
    "THE BLACK IS QUIET FOR A REASON, KID. KEEP YOUR COMMS TIGHT. LET THE ENEMY CHASE ECHOES WHILE YOU STAY UNSEEN. WORDS GET YOU KILLED; QUIET KEEPS YOU BREATHING.",
    "PLANETS SPIN, STARS DIE, AND NOTHING HOLDS STILL, KID. ADAPT TO PULL, STORM, AND SURPRISE OR GET FLUNG INTO FORGOTTEN ORBITS. STAY FLEXIBLE AND STAY ALIVE.",
    "ENEMY BLIPS CLOSING, KID? FLANK HARD RIGHT AND STRAFE LOW. LET THEM CHASE PHANTOMS THROUGH DEBRIS WAKE. DOGFIGHTS ARE KNIFE FIGHTS IN THE DARK.",
    "SHIELDS FLICKERING RED, KID? BREAK INTO EVASIVE SPIRALS NOW. NO STRAIGHT-LINE HEROICS IN A FURBALL. ROLL THE CHAOS, LET THEIR FIRE BITE VACUUM.",
    "TORPEDOES SINGING YOUR NAME, KID? BREAK EARLY, BURN COUNTERMEASURES. DODGE SOON SO YOU CAN COUNTERPUNCH LATE. THE WARHEAD WHISPERS DEATH; YOU ANSWER LOUDER.",
    "OUTNUMBERED, KID? FLY DIRTY THROUGH VENTS AND DEBRIS FIELDS. SPACE JUNK IS A WINGMAN WHEN ODDS STACK HIGH. MAKE THE ENVIRONMENT DO HALF THE KILLING.",
    "MISSILE LOCK BEEPING, KID? FULL BURN, INVERTED ROLL, SHAKE THE GHOST. PANIC IS THE REAL INBOUND THREAT. BREATHE, RESET, THEN TURN HUNTER.",
    "TOUCHDOWN ON ALIEN DIRT, KID? SCAN ATMO BEFORE YOU POP HATCH. DOUBLE-CHECK SUIT SEALS LIKE YOUR LIFE DEPENDS ON IT. WORLDS LIKE THIS BITE BACK.",
    "RUIN SHADOWS HIDE OLD SECRETS, KID, AND OLD TRAPS. PROBE FIRST, STEP SECOND. CURIOSITY PAYS BEST WHEN IT IS DISCIPLINED.",
    "GRAVITY WELL TUGGING YOUR STRUTS, KID? BOOST OUT BEFORE IT WINS. PLANETS LOVE TO KEEP FOOLS AS ORBITAL SCRAP. DO NOT JOIN THE MUSEUM.",
    "EXO-LIFE IN THE MIST, KID? WEAPONS HOT UNTIL PROVEN SAFE. FRIENDLIES DO NOT OPEN WITH CLAWS AND VENOM. CAUTION BUYS OPTIONS.",
    "NEBULA SOUP BLINDS SCOPES, KID. DROP A NAV BEACON FIRST. EGO GETS LOST; BEACONS BRING YOU HOME. MARK THE ROUTE BEFORE YOU NEED IT.",
    "ENGINES RUNNING CHERRY HOT, KID? COOL IN HIGH ORBIT NOW. OVERHEAT IS A SLOW EXECUTION WITH NO RESCUE CREW. MANAGE HEAT LIKE IT IS OXYGEN.",
    "HULL BREACH ALARMS, KID? PATCH FAST AND PURGE THE COMPARTMENT. AIR IS GOLD OUT HERE, PRIDE IS DEAD WEIGHT. SEAL FIRST, TALK LATER.",
    "QUANTUM DRIVE STUTTERING MID-JUMP, KID? MANUAL OVERRIDE AND STEADY HANDS. TECH FAILS; PILOTS FINISH THE JOB. RIDE THE RIPPLE, DO NOT FIGHT IT BLIND.",
    "SENSORS JAMMED TO STATIC, KID? TRUST BACKUPS AND LISTEN TO THE HULL. MACHINES LIE WHEN THE VOID INTERFERES. DISCIPLINE AND INSTINCT KEEP YOU TRUE.",
    "POWER DIPPING LOW, KID? DIVERT TO WEAPONS OVER PRETTY LIGHTS. LUXURY IS FOR DOCKSIDE, SURVIVAL IS FOR NOW. PRIORITIZE OR DIE POLISHED.",
    "CREW PANICKING, KID? STEADY YOUR VOICE AND HOLD THE LINE. THEY FLY YOUR CALM BEFORE THEY FLY YOUR ORDERS. LEAD FROM THE HOT SEAT.",
    "LONE WOLF PLAYS END UGLY, KID. SYNC VECTORS WITH THE SQUAD. PACK TACTICS WIN LONG ENGAGEMENTS. SOLO HEROICS ARE QUICK OBITUARIES.",
    "SMELL BETRAYAL ON COMMS, KID? LOCK CHANNELS AND ISOLATE THE NOISE. TRUST IS EARNED UNDER FIRE, NOT IN BRIEFS. PROTECT THE TEAM FIRST.",
    "MORALE CRATERED AFTER A SCRAPE, KID? REFOCUS THEM ON THE STARS. A BIG SKY MAKES SMALL FEARS MANAGEABLE. RESET THE CREW, THEN RESET THE FIGHT.",
    "OXYGEN TIMER TICKING, KID? SLOW YOUR BREATH AND SHARPEN FOCUS. EACH CONTROLLED INHALE BUYS MORE DECISIONS. WASTE NONE ON PANIC.",
    "BLACK HOLE AHEAD, KID? SLINGSHOT FOR GLORY OR BAIL FOR SURVIVAL. EITHER CHOICE NEEDS COMMITMENT AND CLEAN EXECUTION. HALF MEASURES FEED THE SINGULARITY.",
    "WARP JUMPS SCAR THE SOUL, KID. RESET YOUR MIND AFTER DROP. CLEAR THE GHOSTS BEFORE THEY STEER YOUR HANDS. A CLEAN HEAD FLIES A STRAIGHT SHIP.",
    "VICTORY IS A QUICK HIGH, KID. SURVIVAL BUILDS LEGENDS. LIVE TO LOG THIS RUN, THEN THE NEXT TEN. CONSISTENCY BEATS DRAMA.",
    "STARS DO NOT CARE ABOUT YOUR STORY, KID. MAKE THEM WITNESS IT ANYWAY. BURN BRIGHT WITH INTENT, NOT EGO. LEAVE A TRAIL WORTH FOLLOWING.",
    "THAT IS COMMANDER NICK'S CREED, KID. FLY BOLD ENOUGH TO DIE OLD. BETTER YET, FLY CLEAN ENOUGH TO SKIP DYING ALTOGETHER. NOW MAKE ME PROUD OUT THERE."
};

static inline const char* commander_nick_dialogue(int idx) {
    if (idx < 0) {
        idx = 0;
    }
    return k_commander_nick_dialogues[idx % 30];
}

#endif
