#ifndef PLANETARIUM_PROPAGANDA_H
#define PLANETARIUM_PROPAGANDA_H

static const char* k_planetarium_propaganda_marquee =
    "WAR IS PEACE. VICTORY IS OURS IN THE BATTLE FOR THETA PRI.  "
    "KELVIN ARC FALLS. MINILUV CRUSHES REBELS IN RECORD TIME.  "
    "BIG BROTHER DECLARES TOTAL VICTORY OVER NOVA REACH TRAITORS.  "
    "PEACE THROUGH STRENGTH: 150% PRODUCTION QUOTA SMASHED IN VANTA BELT.  "
    "TELESCREEN PATROLS INCREASED ACROSS EMBER VEIL. EYES EVERYWHERE FOR YOUR SAFETY.  "
    "MINISTRY OF TRUTH CORRECTS RECORDS: ORBITAL IX FAMINE WAS ABUNDANCE.  "
    "CERULEAN RIFT FORCES ANNIHILATED AT THE FRONT. BIG BROTHER LEADS US TO EVERLASTING VICTORY.  "
    "BLACK SITE TRAITORS CRUSHED UNDER MINILUV BOOTS. PRODUCTION SOARS 250% AS WAR EFFORT INTENSIFIES FOR PEACE.  "
    "GLORIOUS BOMBS RAIN ON NOVA REACH PIGS. OUR HEROIC AIRFLEETS SECURE THE SKIES FOR THE PARTY'S ETERNAL RULE.  "
    "FRONTLINES ADVANCE: 10 MILLION ENEMY DEAD. VICTORY GIN ALLOTMENT INCREASED IN THETA PRI.  "
    "KELVIN ARC GUNSHIPS DOWNED IN THOUSANDS. BIG BROTHER'S STRATEGY DELIVERS DOUBLEPLUSGOOD TRIUMPHS DAILY.  "
    "ORBITAL IX ROCKET BOMBS DEVASTATE BLACK SITE. TRAITORS TREMBLE AS WE MARCH TOWARD FINAL TRUTH.  "
    "SWITCH CONFIRMED: NOVA REACH NOW FOES, VANTA BELT NOW ALLIES. MINITRUE UPDATES RECORDS.  "
    "PROLE FACTORIES OUTPRODUCE ENEMY TENFOLD. WAR IS PEACE, PEACE IS OURS THROUGH ENDLESS SACRIFICE.  "
    "BIG BROTHER'S TANKS ROLL OVER CERULEAN RIFT LINES. REPORT SABOTEURS TO KEEP CAMPAIGN FLAWLESS.  "
    "AIRSTRIKES SHATTER EMBER VEIL CITIES. 300% QUOTA MET. JOIN THE TWO MINUTES HATE.  "
    "ENEMY SUBMARINES SUNK IN RECORD NUMBERS. THETA PRI NAVY ENSURES NO INVASION REACHES OUR BELOVED RINGS.  "
    "FRONT REPORT: CASUALTIES MINIMAL, KILLS MAXIMAL. BIG BROTHER SMILES ON OUR PATH TO DOMINATION.  "
    "VANTA BELT ALLIED TURN BETRAYS THEM. OUR MISSILES STRIKE TRUE. VICTORY INEVITABLE UNDER PARTY GUIDANCE.  "
    "BLACK SITE SPIES EXECUTED PUBLICLY. WAR EFFORT UNYIELDING AS TELESCREENS BROADCAST TRIUMPHAL GAINS.  "
    "BOMBER SQUADRONS RETURN HEROIC. FUEL RATION UP 15%. FUEL THE WAR. FUEL THE PARTY. FUEL BIG BROTHER.  ";

#endif
